
fastlane_require "fastlane-plugin-brew"

desc "Lint and test the library"
lane :test do
  brew(command: "install swiftlint")
  swiftlint
  pod_lib_lint
  spm(command: "test")
end

desc "Generate documentation"
lane :doc do
  version = version_get_podspec
  brew(command: "install sourcekitten")
  sh "cd ..; sourcekitten doc --spm-module FTAPIKit > source.json"
  sh "git add ../source.json"
  sh "git stash"
  sh "git checkout gh-pages"
  # Remove all documentation folders
  sh "cd ..; rm -rf Classes Enums Protocols Structs css docsets img js"
  sh "git stash pop"
  jazzy
  sh "mv ../docs/* .."
end
