
TEMPLATE_NAME = 'FTAPIKit'
TEMPLATE_DIR = $(HOME)/Library/Developer/Xcode/Templates/

install:
	mkdir -p $(TEMPLATE_DIR)$(TEMPLATE_NAME) ; \
	cd $(TEMPLATE_NAME) ; \
	cp -R *.xctemplate $(TEMPLATE_DIR)$(TEMPLATE_NAME) ; \
	cd .. ; \

.PHONY = install
