name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: Lint
      run: |
        swiftlint --strict
    - name: Swift build & test
      run: |
        swift build
        swift test
