name: macOS 11

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: |
        swiftlint --strict
    - name: Pod lib lint
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec pod lib lint --allow-warnings
    - name: Swift build & test
      run: |
        swift build
        swift test
